version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.6
      - test-3.5
      - test-2.7
jobs:
  test-2.7: &test-template
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python -m venv venv || virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r test_requirements.txt
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            coverage run --source=aws_okta_keyman setup.py test
            coveralls
      - run:
          name: pycodestyle
          command: |
            . venv/bin/activate
            python setup.py pycodestyle
      - run:
          name: pyflakes
          command: |
            . venv/bin/activate
            python setup.py pyflakes
  test-3.5:
    <<: *test-template
    docker:
      - image: circleci/python:3.5
  test-3.6:
    <<: *test-template
    docker:
      - image: circleci/python:3.6
notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=2r3GsmExITkdgJBGEnGquBymNzhex0UWQ
